readme correction
FandiAR/paras pull request #7
Opened 2020-11-10 07:38 UTC by eccosuprastyo

edit directory "paras in action" point 2

2020-11-10 07:57 UTC, raspiantoro approved these changes

2020-11-10 07:57 UTC, raspiantoro commented on README.md
> +2. Move to /paras directory
need to have some minor revision. use back quote for \`/paras\` so it can be look like this `/paras`. it will give highlihts, and easy to capture by anyone

2020-11-10 07:57 UTC, raspiantoro requested changes

2020-11-10 07:57 UTC, raspiantoro commented on README.md
> +2. Move to /paras directory
see comment above

2020-11-10 08:04 UTC, eccosuprastyo commented on README.md
> +2. Move to /paras directory
okay noted

2020-11-10 09:21 UTC, FandiAR commented on README.md
> +2. Move to /paras directory
Please also add a live demo link [](http://fandiar.github.io/paras)

2020-11-10 10:36 UTC, raspiantoro commented
LGTM 🥳 🎉 🎉 👍

2020-11-10 10:37 UTC, raspiantoro approved these changes

2020-11-10 10:43 UTC, raspiantoro commented
Will be close #6

2020-11-12 04:04 UTC, raspiantoro commented
@FandiAR can we merge this PR?

2020-11-13 15:34 UTC, merged